/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas.Principal;

import BaseDeDatos.GestorClientes;
import BaseDeDatos.GestorContratos;
import BaseDeDatos.GestorEmpleados;
import BaseDeDatos.GestorReservas;
import BaseDeDatos.GestorVehiculos;
import Vistas.Secundarias.PnlClientes;
import Vistas.Secundarias.PnlContrato;
import Vistas.Secundarias.PnlEmpleados;
import Vistas.Secundarias.PnlReservas;
import Vistas.Secundarias.PnlVehiculos;
import javax.swing.JFrame;

/**
 *
 * @author wen
 */
public class FrmPrincipal extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmPrincipal.class.getName());

    private static GestorClientes gestorClientes;
    private static GestorVehiculos gestorVehiculos;
    private static GestorEmpleados gestorEmpleados;
    private static GestorReservas gestorReservas;
    private static GestorContratos gestorContratos;

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        gestorClientes = new GestorClientes();
        gestorVehiculos = new GestorVehiculos();
        gestorEmpleados = new GestorEmpleados();
        gestorReservas = new GestorReservas();
        gestorContratos = new GestorContratos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        btnClientes = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(6);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setMinimumSize(new java.awt.Dimension(400, 40));
        jPanel3.setPreferredSize(new java.awt.Dimension(400, 40));
        jPanel3.setLayout(new java.awt.GridLayout(1, 0, 5, 0));

        btnClientes.setBackground(new java.awt.Color(255, 255, 255));
        btnClientes.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnClientes.setForeground(new java.awt.Color(102, 102, 102));
        btnClientes.setText("Gestor Clientes");
        btnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesActionPerformed(evt);
            }
        });
        jPanel3.add(btnClientes);

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(102, 102, 102));
        jButton4.setText("Gestor Vehiculos");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton4);

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(102, 102, 102));
        jButton5.setText("Gestor Empleados");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton5);

        jButton6.setBackground(new java.awt.Color(255, 255, 255));
        jButton6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(102, 102, 102));
        jButton6.setText("Gestor Reservas");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton6);

        jButton7.setBackground(new java.awt.Color(255, 255, 255));
        jButton7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton7.setForeground(new java.awt.Color(102, 102, 102));
        jButton7.setText("Gestor Contratos");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton7);

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_START);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.BorderLayout());
        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed
        // Limpiar cualquier panel que ya esté dentro
        jPanel1.removeAll();

        // Crear el panel de clientes
        PnlClientes pnlClientes = new PnlClientes(gestorClientes);

        // Agregarlo al panel central (jPanel1) en BorderLayout.CENTER
        jPanel1.add(pnlClientes, java.awt.BorderLayout.CENTER);

        // Refrescar la interfaz
        jPanel1.revalidate();
        jPanel1.repaint();
    }//GEN-LAST:event_btnClientesActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // Limpiar cualquier panel que ya esté dentro
        jPanel1.removeAll();

        // Crear el panel de clientes
        PnlVehiculos pnlClientes = new PnlVehiculos(gestorVehiculos);

        // Agregarlo al panel central (jPanel1) en BorderLayout.CENTER
        jPanel1.add(pnlClientes, java.awt.BorderLayout.CENTER);

        // Refrescar la interfaz
        jPanel1.revalidate();
        jPanel1.repaint();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // Limpiar cualquier panel que ya esté dentro
        jPanel1.removeAll();

        // Crear el panel de clientes
        PnlEmpleados pnlClientes = new PnlEmpleados(gestorEmpleados);

        // Agregarlo al panel central (jPanel1) en BorderLayout.CENTER
        jPanel1.add(pnlClientes, java.awt.BorderLayout.CENTER);

        // Refrescar la interfaz
        jPanel1.revalidate();
        jPanel1.repaint();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // Limpiar cualquier panel que ya esté dentro
        jPanel1.removeAll();

        // Crear el panel de clientes
        PnlReservas pnlClientes = new PnlReservas(gestorReservas, gestorClientes, gestorVehiculos,gestorEmpleados,gestorContratos);

        // Agregarlo al panel central (jPanel1) en BorderLayout.CENTER
        jPanel1.add(pnlClientes, java.awt.BorderLayout.CENTER);

        // Refrescar la interfaz
        jPanel1.revalidate();
        jPanel1.repaint();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
           // Limpiar cualquier panel que ya esté dentro
        jPanel1.removeAll();

        // Crear el panel de clientes
        PnlContrato pnlClientes = new PnlContrato(gestorReservas, gestorClientes, gestorVehiculos,gestorEmpleados,gestorContratos);

        // Agregarlo al panel central (jPanel1) en BorderLayout.CENTER
        jPanel1.add(pnlClientes, java.awt.BorderLayout.CENTER);

        // Refrescar la interfaz
        jPanel1.revalidate();
        jPanel1.repaint();
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClientes;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
